import Image, { ImageProps } from "next/image"
import {
  SiDiscord,
  SiFacebook,
  SiGithub,
  SiGoogle,
  SiInstagram,
  SiPrisma,
  SiSpotify,
  SiX,
} from "@icons-pack/react-simple-icons"
import {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpCircleIcon,
  ArrowUpDown,
  BadgeCheck,
  BarChart,
  Bell,
  BookIcon,
  BookImageIcon,
  BookOpenText,
  Brain,
  Calendar,
  CalendarSearchIcon,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRightIcon,
  ChevronsUpDown,
  Circle,
  Clock,
  CoinsIcon,
  CopyIcon,
  CreditCard,
  DatabaseZapIcon,
  DollarSign,
  File,
  FileBoxIcon,
  FileText,
  Folder,
  GlobeIcon,
  HelpCircle,
  HospitalIcon,
  Image as ImageIcon,
  Inbox,
  Laptop,
  LayoutDashboardIcon,
  LineChartIcon,
  ListIcon,
  Loader2,
  LockIcon,
  LogOut,
  LucideIcon,
  MailIcon,
  MapPin,
  Menu,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  MoveRight,
  PencilIcon,
  PhoneIcon,
  Pizza,
  Plus,
  PuzzleIcon,
  SaveIcon,
  Search,
  Settings,
  Shield,
  Sparkles,
  SquareTerminal,
  Stethoscope,
  SunMedium,
  ToggleRightIcon,
  Trash,
  TrendingDown,
  TrendingUp,
  UserCircleIcon,
  UserCogIcon,
  UserPlus,
  Users,
  X,
  ZapIcon,
} from "lucide-react"
import { SiLinkedin } from "react-icons/si"

export type Icon = LucideIcon

function LogoIcon({
  className,
  ...props
}: {
  className?: string
  props?: ImageProps
}) {
  return <Image src="/author.jpg" alt="Logo" className={className} {...props} />
}

export const Icons = {
  logo: LogoIcon,
  logoLucide: ChevronsRightIcon,
  close: X,
  up: ArrowUp,
  down: ArrowDown,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: ImageIcon,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: UserCircleIcon,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  search: Search,
  check: Check,
  orderbook: BookOpenText,
  chevronsUpDown: ChevronsUpDown,
  phone: PhoneIcon,
  mail: MailIcon,
  pencil: PencilIcon,
  student: PencilIcon,
  teacher: UserCogIcon,
  monitor: Monitor,
  lock: LockIcon,
  puzzle: PuzzleIcon,
  globe: GlobeIcon,
  databaseZap: DatabaseZapIcon,
  blog: BookImageIcon,
  graph: LineChartIcon,
  zap: ZapIcon,
  copy: CopyIcon,
  toggleRight: ToggleRightIcon,
  creditCard: CreditCard,
  calendar: Calendar,
  barChart: BarChart,
  clock: Clock,
  brain: Brain,
  menu: Menu,
  document: BookIcon,
  folder: Folder,
  more: MoreHorizontal,
  badgeCheck: BadgeCheck,
  bell: Bell,
  logOut: LogOut,
  sparkles: Sparkles,
  studio: SquareTerminal,
  register: UserPlus,
  appointment: CalendarSearchIcon,
  coins: CoinsIcon,
  location: MapPin,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  dollarSign: DollarSign,
  users: Users,
  inbox: Inbox,
  arrowUpDown: ArrowUpDown,
  circle: Circle,
  helpCircle: HelpCircle,
  shield: Shield,
  therapist: Stethoscope,
  staff: Users,
  pending: Loader2,
  approved: Check,
  rejected: X,
  contacted: MailIcon,
  demoScheduled: CalendarSearchIcon,
  demoCompleted: Check,
  contractSigned: FileText,
  onboarding: UserCogIcon,
  joined: UserPlus,
  save: SaveIcon,
  question: HelpCircle,
  clinic: HospitalIcon,
  edit: PencilIcon,
  userPlus: UserPlus,
  leave: LogOut,
  chevronDown: ChevronDown,
  dashboard: LayoutDashboardIcon,
  lifecycle: ListIcon,
  arrowUpCircle: ArrowUpCircleIcon,
  discord: SiDiscord,
  github: SiGithub,
  google: SiGoogle,
  prisma: SiPrisma,
  x: SiX,
  linkedin: SiLinkedin,
  facebook: SiFacebook,
  instagram: SiInstagram,
  moveRight: MoveRight,
  spotify: SiSpotify,
  file: FileBoxIcon,
  arrowLeft: ArrowLeft,
}
